
services:
  ui:
    depends_on:
      - api
      - redis
    build: 
      context: ./frontend
    ports:
      - 3000:3000
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync

  api:
    depends_on:
      - redis
    build: 
      context: ./api
    image: qgenie-api
    ports:
      - 8000:8000
    develop:
      watch:
        - path: ./api/requirements.txt
          action: rebuild
        - path: ./api
          target: /app
          action: sync
  
  redis:  
    image: redis:7.0.11-alpine
    hostname: redis-server
    ports:
      - 6379:6379
  
  worker:
    image: qgenie-api
    depends_on:
        - redis
    command: rqworker --url redis://redis-server:6379 chat_queue
    links:
        - redis

