"use client"

import type { Metadata } from 'next'
import { RecoilRoot } from 'recoil';
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/Theme'
import {
  QueryClient,
  QueryClientProvider,
} from '@tanstack/react-query'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'QuantGenie',
//   description: 'Generated by create next app',
// }

const queryClient = new QueryClient()

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
        <body className={inter.className}>
          <RecoilRoot>
            <QueryClientProvider client={queryClient}>
              <ThemeProvider
                  attribute="class"
                  defaultTheme="dark"
                  enableSystem
                  disableTransitionOnChange
              >
                {children}
              </ThemeProvider>
            </QueryClientProvider>
          </RecoilRoot>
        </body>
      
    </html>
  )
}
